# Generated by Django 6.0.4 on 2026-05-10 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('P2PTrade', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
