# Generated by Django 6.0.4 on 2026-05-10 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('marketplace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('foreign_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('myr_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('evidence', models.TextField(blank=True, null=True)),
                ('seller_confirmation_status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_from', to='core.currency')),
                ('raised_by', models.ForeignKey(help_text='Either buyer or seller who raised the dispute', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_as_seller', to=settings.AUTH_USER_MODEL)),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_to', to='core.currency')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispute', to='marketplace.transaction')),
            ],
            options={
                'db_table': 'disputes',
            },
        ),
        migrations.CreateModel(
            name='DisputeActivityLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='disputes.dispute')),
            ],
            options={
                'db_table': 'dispute_activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('is_admin_message', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='disputes.dispute')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeResolution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resolution_type', models.CharField(choices=[('release_to_buyer', 'Release to Buyer'), ('return_to_seller', 'Return to Seller'), ('partial_split', 'Partial Split')], max_length=20)),
                ('buyer_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('seller_refund_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('resolution_notes', models.TextField()),
                ('resolved_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resolution', to='disputes.dispute')),
                ('resolved_by_admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_resolutions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dispute_resolutions',
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['transaction'], name='disputes_transac_6a360f_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['buyer'], name='disputes_buyer_i_17080a_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['seller'], name='disputes_seller__0697f2_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status'], name='disputes_status_811094_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['created_at'], name='disputes_created_263e71_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeactivitylog',
            index=models.Index(fields=['dispute'], name='dispute_act_dispute_dd180d_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeactivitylog',
            index=models.Index(fields=['timestamp'], name='dispute_act_timesta_970cb3_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['dispute'], name='dispute_mes_dispute_e45b2b_idx'),
        ),
        migrations.AddIndex(
            model_name='disputemessage',
            index=models.Index(fields=['created_at'], name='dispute_mes_created_10be79_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeresolution',
            index=models.Index(fields=['dispute'], name='dispute_res_dispute_e7849e_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeresolution',
            index=models.Index(fields=['resolved_by_admin'], name='dispute_res_resolve_b99820_idx'),
        ),
    ]
