# Generated by Django 6.0.4 on 2026-05-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='evidence',
            field=models.FileField(blank=True, null=True, upload_to='disputes/evidence/'),
        ),
    ]
