# Generated by Django 6.0.4 on 2026-05-10 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'Currencies',
                'db_table': 'currencies',
            },
        ),
        migrations.CreateModel(
            name='ActivityRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('exchange', 'Exchange'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_records', to=settings.AUTH_USER_MODEL)),
                ('from_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_from', to='core.currency')),
                ('to_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activities_to', to='core.currency')),
            ],
            options={
                'db_table': 'activity_records',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user'], name='activity_re_user_id_3563ae_idx'), models.Index(fields=['timestamp'], name='activity_re_timesta_229078_idx'), models.Index(fields=['activity_type'], name='activity_re_activit_e1c988_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, help_text='Percentage change indicator', max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='core.currency')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='core.currency')),
            ],
            options={
                'db_table': 'exchange_rates',
                'indexes': [models.Index(fields=['from_currency'], name='exchange_ra_from_cu_6cb1d0_idx'), models.Index(fields=['to_currency'], name='exchange_ra_to_curr_a417fb_idx')],
                'unique_together': {('from_currency', 'to_currency')},
            },
        ),
    ]
