# Generated by Django 6.0.4 on 2026-05-10 04:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], max_length=4)),
                ('status', models.CharField(choices=[('active', 'Active'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals_from', to='core.currency')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_deals', to=settings.AUTH_USER_MODEL)),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals_to', to='core.currency')),
            ],
            options={
                'db_table': 'deals',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('exchange', 'Exchange'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('offer_created', 'Offer Created'), ('purchase', 'Purchase'), ('sale', 'Sale')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('awaiting_confirmation', 'Awaiting Confirmation')], max_length=25)),
                ('tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('proof_of_payment', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='marketplace.deal')),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_from', to='core.currency')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_to', to='core.currency')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['seller'], name='deals_seller__29211a_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status'], name='deals_status_eeb583_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['created_at'], name='deals_created_7fb120_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['expires_at'], name='deals_expires_83330b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['buyer'], name='transaction_buyer_i_56e41a_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['seller'], name='transaction_seller__083d37_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['type'], name='transaction_type_840495_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['deal'], name='transaction_deal_id_9e65dd_idx'),
        ),
    ]
