# Generated by Django 6.0.4 on 2026-06-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='balance_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
