# Generated by Django 6.0.4 on 2026-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_deal_balance_reserved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('exchange', 'Exchange'), ('purchase', 'Purchase'), ('sale', 'Sale')], max_length=20),
        ),
    ]
